### ISSUE TITLE
`npm start` TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by AlexRadch** [eigenmethod/mol#291]
`npm start` show next next error in console in Windows.
```
> @ start C:\Folder\mam
> node ./mol/build/-/node.test.js

TypeError: > @ start C:\Folder\mam
> node ./mol/build/-/node.test.js

TypeError: Cannot read property '1' of null
    at Object.$mol_func_name (C:\Folder\mam\mol\func\name\name.ts:9:98)
    at Function.toString (C:\Folder\mam\mol\object\object.ts:21:11)
    at dom_name (C:\Folder\mam\mol\view\view.ts:84:28)
    at dom_node (C:\Folder\mam\mol\view\view.ts:149:104)
    at $mol_atom.handler (C:\Folder\mam\mol\mem\mem.ts:20:22)
    at $mol_atom.pull (C:\Folder\mam\mol\atom\atom.ts:120:17)
    at $mol_atom.actualize (C:\Folder\mam\mol\atom\atom.ts:105:23)
    at $mol_atom.get (C:\Folder\mam\mol\atom\atom.ts:57:9)
    at $mol_atom.value (C:\Folder\mam\mol\atom\atom.ts:288:16)
    at $mol_mem_value (C:\Folder\mam\mol\mem\mem.ts:42:16)'1' of null
    at Object.$mol_func_name (C:\Folder\mam\mol\func\name\name.ts:9:98)
    at Function.toString (C:\Folder\mam\mol\object\object.ts:21:11)
    at dom_name (C:\Folder\mam\mol\view\view.ts:84:28)
    at dom_node (C:\Folder\mam\mol\view\view.ts:149:104)
    at $mol_atom.handler (C:\Folder\mam\mol\mem\mem.ts:20:22)
    at $mol_atom.pull (C:\Folder\mam\mol\atom\atom.ts:120:17)
    at $mol_atom.actualize (C:\Folder\mam\mol\atom\atom.ts:105:23)
    at $mol_atom.get (C:\Folder\mam\mol\atom\atom.ts:57:9)
    at $mol_atom.value (C:\Folder\mam\mol\atom\atom.ts:288:16)
    at $mol_mem_value (C:\Folder\mam\mol\mem\mem.ts:42:16)
```

**Comment by Rurik19** [comment]
I have that error too. But it seems that all work, however.

**Comment by nin-jin** [comment]
What are NodeJS version you using?

**Comment by Rurik19** [comment]
v8.0.0

**Comment by nin-jin** [comment]
Can you update nodejs to 9 version?

**Comment by AlexRadch** [comment]
node 8 is recommended for most users. See https://nodejs.org/en/download/

**Comment by nin-jin** [comment]
https://github.com/eigenmethod/mol/commit/0850f2868b347bb17597271adf9db04b3405a59e
