### ISSUE TITLE
$mol_build: Иногда, в процессе работы валится dev-server

### ISSUE THREAD

**Issue by zerkalica** [eigenmethod/mol#370]
Походу утечки лисенеров где-то.
Возможно #355 тоже из-за этого жрет.

```
352:54)
    at $mol_build.root("/home/yuferev/projects/mpk-dev").server().generator("/mol/app/report/-/web.js").get (/home/yuferev/projects/mpk-dev/mol/atom2/atom2.ts:65:24)
    at $.$mol_fiber.run (/home/yuferev/projects/mpk-dev/mol/mem/key/key.ts:58:45)
    at <$mol_fiber>/0:.pull (/home/yuferev/projects/mpk-dev/mol/fiber/fiber.ts:305:20)
    at <$mol_fiber>/0:.update (/home/yuferev/projects/mpk-dev/mol/fiber/fiber.ts:322:10)
    at <$mol_fiber>/0:.get (/home/yuferev/projects/mpk-dev/mol/fiber/fiber.ts:352:54)
    at <anonymous>|$mol_fiber (/home/yuferev/projects/mpk-dev/mol/fiber/fiber.ts:177:19)
    at $mol_fiber.run (/home/yuferev/projects/mpk-dev/mol/wrapper/wrapper.ts:9:28)
13:56:54 Built mol/app/report/-/web.js
13:56:54 Built mol/app/report/-/web.esm.js
mol/expander/expander.view.tree> git --no-pager log --oneline HEAD..origin/master
spawnSync /bin/sh ENOTDIR
mol/textarea/textarea.view.tree> git --no-pager log --oneline HEAD..origin/master
spawnSync /bin/sh ENOTDIR
mol/app/studio/field/field.view.tree> git --no-pager log --oneline HEAD..origin/master
spawnSync /bin/sh ENOTDIR
mol/app/studio/studio.view.tree> git --no-pager log --oneline HEAD..origin/master
spawnSync /bin/sh ENOTDIR
14:03:15 Built mol/app/studio/-/web.css
14:03:15 Built mol/app/studio/-/index.html
14:03:20 Built mol/app/studio/-/web.js
14:03:20 Built mol/app/studio/-/web.esm.js
(node:27484) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
(node:27484) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
(node:27484) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
(node:27484) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
(node:27484) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
(node:27484) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
14:03:21 Built mol/app/studio/-/web.locale=en.json
Not translated to "en": $mol_app_studio_prop_add_label
14:03:21 Built mol/app/studio/-/web.locale=ru.json
mol/app/todomvc/todomvc.view.tree> git --no-pager log --oneline HEAD..origin/master
spawnSync /bin/sh ENOTDIR
14:07:32 Built mol/app/todomvc/-/web.css
14:07:32 Built mol/app/todomvc/-/index.html
14:07:32 Built mol/app/todomvc/-/mol/app/todomvc/todomvc_active.svg
14:07:32 Built mol/app/todomvc/-/mol/app/todomvc/todomvc_completed.svg
14:07:35 Built mol/app/todomvc/-/web.js
14:07:36 Built mol/app/todomvc/-/web.esm.js
(node:27484) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
14:07:39 Built mol/app/todomvc/-/web.test.js
(node:27484) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
(node:27484) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
mol/app/calc/calc.view.tree> git --no-pager log --oneline HEAD..origin/master
spawnSync /bin/sh ENOTDIR
14:07:56 Built mol/app/calc/-/web.css
14:07:56 Built mol/app/calc/-/index.html
14:08:01 Built mol/app/calc/-/web.js
14:08:02 Built mol/app/calc/-/web.esm.js
(node:27484) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
(node:27484) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
14:08:02 Built mol/app/calc/-/web.locale=en.json
14:08:02 Built mol/app/calc/-/web.locale=ru.json
mol/app/habhub/habhub.view.tree> git --no-pager log --oneline HEAD..origin/master
spawnSync /bin/sh ENOTDIR
14:09:27 Built mol/app/habhub/-/web.css
14:09:27 Built mol/app/habhub/-/index.html

<--- Last few GCs --->

[27484:0x43f18d0] 11995691 ms: Mark-sweep 1371.9 (1426.2) -> 1371.6 (1426.7) MB, 1322.8 / 0.0 ms  (average mu = 0.126, current mu = 0.003) allocation failure scavenge might not succeed
[27484:0x43f18d0] 11997060 ms: Mark-sweep 1372.3 (1426.7) -> 1372.0 (1427.2) MB, 1366.1 / 0.0 ms  (average mu = 0.068, current mu = 0.002) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0xc55e80dbe1d]
Security context: 0x12917bc9e6e9 <JSObject>
    1: new Map(aka Map) [0x12917bc91b59](this=0x2f7879402801 <the_hole>)
    2: ConstructFrame [pc: 0xc55e808d145]
    3: bindContainer(aka bindContainer) [0x44210ba82d1] [/home/yuferev/projects/mpk-dev/node_modules/typescript/lib/typescript.js:~28030] [pc=0xc55ec6ddfe7](this=0x2f78794026f1 <undefined>,node=0x07de431e1e91 <NodeObject map = 0x3db818595291>,con...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x8dc510 node::Abort() [node]
 2: 0x8dc55c  [node]
 3: 0xad9b5e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xad9d94 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xec7bf2  [node]
 6: 0xec7cf8 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [node]
 7: 0xed3dd2 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xed4704 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xed7371 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [node]
10: 0xea07f4 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [node]
11: 0x114018e v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [node]
12: 0xc55e80dbe1d 
Aborted
```

**Comment by zerkalica** [comment]
Может просто памяти не хватает, всего 8 гигов.

**Comment by nin-jin** [comment]
Ты понаоткрывал кучу приложений - они все начинают инкрементально билдиться.
Вообще, да, стоит сделать, чтобы кеш жил только для последнего приложения.

**Comment by zerkalica** [comment]
> MaxListenersExceededWarning: Possible EventEmitter memory leak detected

Это смущает.

https://github.com/nodejs/node/issues/29239

**Comment by zerkalica** [comment]
вроде не актуально, было мало свободной памяти

**Comment by nin-jin** [comment]
Так может закрыть?
