### ISSUE TITLE
Error about $mol_icon_chevron in travis

### ISSUE THREAD

**Issue by nin-jin** [eigenmethod/mol#61]
```
Error: 
/home/travis/build/eigenmethod/mol/app/demo/-/view.tree/demo.view.tree.ts:83:13
 Cannot find name '$mol_icon_chevron'.
/home/travis/build/eigenmethod/mol/app/supplies/detailer/-/view.tree/detailer.view.tree.ts:16:13
 Cannot find name '$mol_icon_chevron'.
/home/travis/build/eigenmethod/mol/checker/expander/-/view.tree/expander.view.tree.ts:6:13
 Cannot find name '$mol_icon_chevron'.
    at $mol_build.sourcesJS (/home/travis/build/eigenmethod/mol/build/build.node.ts:236:29)
    at $mol_atom.pull (/home/travis/build/eigenmethod/mol/atom/atom.ts:128:26)
    at $mol_atom.actualize (/home/travis/build/eigenmethod/mol/atom/atom.ts:117:21)
    at $mol_atom.get (/home/travis/build/eigenmethod/mol/atom/atom.ts:71:9)
    at $mol_build.descr.value [as sourcesJS] (/home/travis/build/eigenmethod/mol/mem/mem.ts:82:17)
    at $mol_build.bundleJS (/home/travis/build/eigenmethod/mol/build/build.node.ts:434:23)
    at $mol_atom.pull (/home/travis/build/eigenmethod/mol/atom/atom.ts:128:26)
    at $mol_atom.actualize (/home/travis/build/eigenmethod/mol/atom/atom.ts:117:21)
    at $mol_atom.get (/home/travis/build/eigenmethod/mol/atom/atom.ts:71:9)
    at $mol_build.descr.value [as bundleJS] (/home/travis/build/eigenmethod/mol/mem/mem.ts:82:17)
```

Ещё и не падает при ошибке.

Локально на винде не воспроизводится.

**Comment by camom1le** [comment]
Под маком вообще не запускается ни одна демка по той же причине, впрочем я не могу найти определения mol_icon_chevron нигде в коде, смазывает первое впечатление от фреймворка - начать работу невозможно

**Comment by nin-jin** [comment]
Ага, не закоммичен был.
